title: andi2
description: blog about software development, programming and other fun topics
theme: minima

minima:
  skin: dark
  social_links:
    - title: LinkedIn
      icon: linkedin
      url: "https://linkedin.com/in/andreaslauer"
    - title: Email
      icon: envelope
      type: solid
      url: "mailto:andreaslauer90@googlemail.com"
url: "https://andi2.com"
baseurl: ""
